//Post Rating
export const PARENT_POST_RATING_START = "PARENT_POST_RATING_START";
export const PARENT_POST_RATING_SUCCESS = "PARENT_POST_RATING_SUCCESS";
export const PARENT_POST_RATING_FAILURE = "PARENT_POST_RATING_FAILURE";
