//Get teacher info
export const GET_ALL_CLASSES_START = "GET_ALL_CLASSES_START";
export const GET_ALL_CLASSES_SUCCESS = "GET_ALL_CLASSES_SUCCESS";
export const GET_ALL_CLASSES_FAILURE = "GET_ALL_CLASSES_FAILURE";
