//Add Class
export const ADD_CLASS_START = "ADD_CLASS_START";
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const ADD_CLASS_FAILURE = "ADD_CLASS_FAILURE";

//Add question
export const ADD_QUESTION_START = "ADD_QUESTION_START";
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS";
export const ADD_QUESTION_FAILURE = "ADD_QUESTION_FAILURE";

//Get Question By Class Id
export const GET_QUESTIONS_BY_CLASS_START = "GET_QUESTIONS_BY_CLASS_START";
export const GET_QUESTIONS_BY_CLASS_SUCCESS = "GET_QUESITONS_BY_CLASS_SUCCESS";
export const GET_QUESTIONS_BY_CLASS_FAILURE = "GET_QUESTIONS_BY_CLASS_FAILURE";

//Delete Question By Question Id
export const DELETE_QUESTION_BY_ID_START = "DELETE_QUESTION_BY_ID_START";
export const DELETE_QUESTION_BY_ID_SUCCESS = "DELETE_QUESTION_BY_ID_SUCCESS";
export const DELETE_QUESTION_BY_ID_FAILURE = "DELETE_QUESTION_BY_ID_FAILURE";

//Update Question
export const UPDATE_QUESTION_START = "UPDATE_QUESTION_START";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_FAILURE = "UPDATE_QUESTION_FAILURE";
